// turbo_scripts.js — generated from gump.scripts via gump.transpile_js
// Source of truth: gump/scripts.py (Turbo source).
// Regenerate with: python -c "from gump.transpile_js import to_js_module; from gump.scripts import SCRIPTS; ..."
// All threshold logic on this site flows from these Turbo programs.
// ============================================================
// Turbo JS runtime — K, R, E, T + stdlib, generated by gump.transpile_js
// ============================================================
// NOTE: these were `const`, which throws "already declared" on any page that also
// loads k-colors.js (which declares a global `var PHI`/`INV_PHI` first) — silently
// breaking this whole script on foldwatch/sensor/chipfast pages. Changed to `var`
// (identical values either way) since var-var redeclaration is legal, const-var isn't.
// If this file gets regenerated from gump/scripts.py, mirror this fix at the source.
var PHI = (1 + Math.sqrt(5)) / 2;
var INV_PHI = 1 / PHI;
var K_c = 1.868122;
var K_BKT = 2 / Math.PI;
var alpha = 1 / 137.036;
var pi = Math.PI;
var e = Math.E;
var phi = PHI;

function _num(x) {
  if (typeof x === 'number') return x;
  if (typeof x === 'boolean') return x ? 1 : 0;
  throw new TypeError('expected number');
}

function _list(x, op) {
  if (!Array.isArray(x)) throw new TypeError(op + ': expected list');
  return x;
}

function _truthy(v) {
  if (v === null || v === undefined || v === false) return false;
  if (typeof v === 'number') return v !== 0;
  if (typeof v === 'string') return v.length > 0;
  if (Array.isArray(v)) return v.length > 0;
  return true;
}

function _plus(a, b) {
  if (Array.isArray(a) && Array.isArray(b)) return a.concat(b);
  return a + b;
}

// Framework primitives
function K(x) { x = _num(x); return x / (1 + x); }
function R(x) { x = _num(x); return 1 / (1 + 1 / Math.max(0.001, x)); }
function E(x) { return _num(x) * 2.87e-21; }
function T(x) { x = _num(x); return Math.max(0, K(x) - R(x)); }

// Math
function abs(x) { return Math.abs(_num(x)); }
function sqrt(x) { return Math.sqrt(_num(x)); }
function exp(x) { return Math.exp(_num(x)); }
function log(x) { return Math.log(_num(x)); }
function sin(x) { return Math.sin(_num(x)); }
function cos(x) { return Math.cos(_num(x)); }
function tan(x) { return Math.tan(_num(x)); }
function floor(x) { return Math.floor(_num(x)); }
function ceil(x) { return Math.ceil(_num(x)); }
function round(x, d) {
  if (d === undefined) return Math.round(_num(x));
  const f = Math.pow(10, d);
  return Math.round(_num(x) * f) / f;
}

// Aggregates
function max(...args) {
  if (args.length === 1 && Array.isArray(args[0])) return Math.max(...args[0]);
  return Math.max(...args);
}
function min(...args) {
  if (args.length === 1 && Array.isArray(args[0])) return Math.min(...args[0]);
  return Math.min(...args);
}
function sum(lst) { return _list(lst, 'sum').reduce((a, b) => a + b, 0); }
function product(lst) { return _list(lst, 'product').reduce((a, b) => a * b, 1); }
function mean(lst) {
  lst = _list(lst, 'mean');
  if (lst.length === 0) throw new Error('mean: empty list');
  return sum(lst) / lst.length;
}

// Higher-order
function map(f, lst) { return _list(lst, 'map').map(x => f(x)); }
function reduce(f, lst, ...rest) {
  lst = _list(lst, 'reduce');
  if (rest.length > 0) return lst.reduce((a, b) => f(a, b), rest[0]);
  if (lst.length === 0) throw new Error('reduce: empty list');
  return lst.slice(1).reduce((a, b) => f(a, b), lst[0]);
}
function filter(f, lst) { return _list(lst, 'filter').filter(x => _truthy(f(x))); }

// List ops
function length(x) {
  if (Array.isArray(x) || typeof x === 'string') return x.length;
  throw new TypeError('length: expected list or string');
}
function head(lst) {
  lst = _list(lst, 'head');
  if (lst.length === 0) throw new Error('head: empty list');
  return lst[0];
}
function tail(lst) { return _list(lst, 'tail').slice(1); }
function append(lst, x) { return _list(lst, 'append').concat([x]); }
function concat(a, b) {
  if (Array.isArray(a) && Array.isArray(b)) return a.concat(b);
  // String concat varargs
  return Array.from(arguments).map(x => String(x)).join('');
}
function range(...args) {
  let a, b, step;
  if (args.length === 1) { a = 0; b = args[0]; step = 1; }
  else if (args.length === 2) { a = args[0]; b = args[1]; step = 1; }
  else { a = args[0]; b = args[1]; step = args[2]; }
  const out = [];
  if (step > 0) for (let i = a; i < b; i += step) out.push(i);
  else if (step < 0) for (let i = a; i > b; i += step) out.push(i);
  else throw new Error('range: step cannot be 0');
  return out;
}

// Coupling-specific
function kuramoto_R(thetas) {
  thetas = _list(thetas, 'kuramoto_R');
  if (thetas.length === 0) return 0;
  let cx = 0, sy = 0;
  for (const t of thetas) { cx += Math.cos(_num(t)); sy += Math.sin(_num(t)); }
  cx /= thetas.length; sy /= thetas.length;
  return Math.sqrt(cx * cx + sy * sy);
}
function phase_diff(a, b) {
  let d = (_num(a) - _num(b)) % (2 * Math.PI);
  if (d > Math.PI) d -= 2 * Math.PI;
  if (d <= -Math.PI) d += 2 * Math.PI;
  return d;
}
function entropy(ps) {
  ps = _list(ps, 'entropy');
  if (ps.length === 0) return 0;
  let total = 0;
  for (const p of ps) total += _num(p);
  if (total <= 0) return 0;
  let h = 0;
  for (const p of ps) {
    const q = _num(p) / total;
    if (q > 0) h -= q * Math.log(q);
  }
  return h;
}
function fib(n) {
  n = Math.floor(_num(n));
  let a = 0, b = 1;
  for (let i = 0; i < n; i++) [a, b] = [b, a + b];
  return a;
}

// String ops
function upper(s) { return String(s).toUpperCase(); }
function lower(s) { return String(s).toLowerCase(); }
function trim(s) { return String(s).trim(); }
function contains(s, sub) { return String(s).includes(String(sub)); }
function split(s, sep) { return String(s).split(String(sep)); }
function join(sep, lst) { return _list(lst, 'join').map(String).join(String(sep)); }
function replace(s, oldstr, newstr) {
  return String(s).split(String(oldstr)).join(String(newstr));
}
function str(x) {
  if (typeof x === 'number' && Number.isInteger(x)) return String(x);
  return String(x);
}
function num(x) {
  if (typeof x === 'number') return x;
  const s = String(x);
  return s.indexOf('.') >= 0 || s.indexOf('e') >= 0 ? parseFloat(s) : parseInt(s, 10);
}

function _print(...args) {
  if (typeof console !== 'undefined') console.log(...args);
  return args.length ? args[args.length - 1] : undefined;
}
// expose `print` (matches Turbo name)
const print = _print;


// --- k_reading ---
function k_reading(k) {
  const k_reading = (k) => (_truthy((k < 0.2)) ? "barely any connection" : (_truthy((k < 0.5)) ? "loosely coupled" : (_truthy((k < 0.9)) ? "moderate coupling" : (_truthy((k < 1.3)) ? "well coupled" : (_truthy((k < 1.6)) ? "strongly coupled" : (_truthy((k < 1.87)) ? "near the ceiling (1.868)" : "at the hard ceiling"))))));
  return k_reading(k);
}

// --- r_reading ---
function r_reading(r) {
  const r_reading = (r) => (_truthy((r < 0.2)) ? "no shared rhythm yet" : (_truthy((r < 0.5)) ? "some coherence building" : (_truthy((r < 0.59)) ? "approaching the sweet spot (0.618)" : (_truthy((r < 0.67)) ? "right at the sweet spot" : (_truthy((r < 0.85)) ? "well synchronized" : (_truthy((r < 0.97)) ? "tightly locked in" : "perfectly synchronized"))))));
  return r_reading(r);
}

// --- t_reading ---
function t_reading(t) {
  const t_reading = (t) => (_truthy((t < 0.03)) ? "no tension (stable)" : (_truthy((t < 0.15)) ? "some healthy tension" : (_truthy((t < 0.4)) ? "high tension" : "very high tension")));
  return t_reading(t);
}

// --- classify_regime ---
function classify_regime(k, r) {
  const classify = (k, r) => (_truthy(((k > 0.8) && (r > 0.6))) ? "locked" : (_truthy(((k > 0.5) && (r > 0.3))) ? "coherent" : (_truthy((k > 0.3)) ? "transitional" : "free")));
  return classify(k, r);
}

// --- sync_summary ---
function sync_summary(phases) {
  const sync = kuramoto_R(phases);
  const regime = (_truthy((sync > 0.9)) ? "fully synchronized" : (_truthy((sync > 0.6)) ? "partially synchronized" : (_truthy((sync > 0.3)) ? "weak coupling" : "incoherent")));
  return [sync, regime];
}
