(function(){
'use strict';
var cv=document.getElementById('g-canvas');if(!cv)return;var cx=cv.getContext('2d');
var cfg=window.GUMP_ART||{},W=0,H=0,dpr=1,t=0,TAU=Math.PI*2,PHI=(1+Math.sqrt(5))/2,GA=2.39996322;
var reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,word=document.querySelector('.g-word'),meter=document.querySelector('.g-meter');
var s={points:[],dust:[],trails:[],pairs:[],heat:[],R:0,T:1,lastMove:performance.now()};
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}function smooth(x){x=clamp(x,0,1);return x*x*(3-2*x)}
function rgba(c,a){return 'rgba('+c[0]+','+c[1]+','+c[2]+','+clamp(a,0,1).toFixed(4)+')'}
function col(n){var p={gold:[184,117,58],light:[232,207,160],rose:[210,150,120],blue:[110,160,210],green:[90,173,90],violet:[190,140,200],amber:[201,164,74]};return p[n]||p.gold}
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;cv.width=W*dpr;cv.height=H*dpr;cx.setTransform(dpr,0,0,dpr,0,0);init()}
function dustSeed(n){s.dust=[];for(var i=0;i<n;i++)s.dust.push({x:Math.random()*W,y:Math.random()*H,p:Math.random()*TAU,v:Math.random(),z:.4+Math.random()*.9})}
function init(){var mode=modeName();s.points=[];s.trails=[];s.pairs=[];s.heat=[];dustSeed(reduced?140:420);var i,a,r;if(mode==='first-frequency'){for(i=0;i<137;i++){a=i*GA;r=Math.sqrt(i)/Math.sqrt(137)*Math.min(W,H)*.35;s.points.push({x:W/2+Math.cos(a)*r,y:H/2+Math.sin(a)*r,p:Math.random()*TAU,o:.2+Math.random()*.6,lock:0})}}
else if(mode==='catching-up'){s.trails=[[],[]]}
else if(mode==='real-part'){for(i=0;i<24;i++)spawnPair()}
else if(mode==='two-voices'){for(i=0;i<2;i++)s.points.push({x:W*(.38+i*.24),y:H/2,p:i*Math.PI,o:i?1.618:1})}
else if(mode==='strings'){for(i=0;i<13;i++)s.points.push({x:W*(.14+i*.06),y:H*.22,p:Math.random()*TAU,o:.4+i*.08})}
else if(mode==='still-here'){for(i=0;i<33;i++)s.points.push({x:Math.random()*W,y:Math.random()*H,p:Math.random()*TAU,r:18+Math.random()*90,o:.25+Math.random()*.8})}
else {for(i=0;i<137;i++){a=i*GA;r=Math.sqrt(i)/Math.sqrt(137)*Math.min(W,H)*.34;s.points.push({x:W/2+Math.cos(a)*r,y:H/2+Math.sin(a)*r,p:Math.random()*TAU,o:.2+Math.random()*.8})}}
}
function modeName(){var title=(document.title||'').toLowerCase();if(title.indexOf('still here')>=0)return 'still-here';return cfg.mode||'field'}
function bg(a){var b=cfg.bg||[6,3,2];cx.fillStyle='rgba('+b[0]+','+b[1]+','+b[2]+','+a.toFixed(3)+')';cx.fillRect(0,0,W,H)}
function dust(m){for(var i=0;i<s.dust.length;i++){var d=s.dust[i];d.p+=.006+m*.012;d.v=d.v*.985+(Math.sin(d.p+i)*.5+.5)*m*.025;d.x+=Math.cos(d.p)*(.08+m*.22)*d.z;d.y+=Math.sin(d.p*.7)*(.08+m*.18)*d.z;if(d.x<0)d.x=W;if(d.x>W)d.x=0;if(d.y<0)d.y=H;if(d.y>H)d.y=0;cx.fillStyle=rgba(col('gold'),.008+d.v*.075);cx.fillRect(d.x,d.y,1,1)}}
function dot(x,y,c,a,r){var g=cx.createRadialGradient(x,y,0,x,y,r*7);g.addColorStop(0,rgba(c,a*.32));g.addColorStop(1,rgba(c,0));cx.fillStyle=g;cx.beginPath();cx.arc(x,y,r*7,0,TAU);cx.fill();cx.fillStyle=rgba(c,a);cx.beginPath();cx.arc(x,y,r,0,TAU);cx.fill()}
function spawnPair(){s.pairs.push({a:(Math.random()-.5)*1.6,b:.2+Math.random()*.75,p:Math.random()*TAU,z:.45+Math.random()*.75,w:0})}
function firstFrequency(){var m=smooth((t-1)/9),sig=smooth((t-5)/18),couple=smooth((t-14)/28);bg(.17-m*.09);cx.globalCompositeOperation='lighter';dust(m);for(var i=0;i<s.points.length;i++){var p=s.points[i];p.p+=.004+sig*.017;p.lock+=(couple-p.lock)*.01;p.x+=(W/2-p.x)*p.lock*.004;p.y+=(H/2-p.y)*p.lock*.004;var br=.5+.5*Math.sin(p.p),a=(sig*.05+br*.03*sig)*(1-i/190),r=1+br*2+couple*2;dot(p.x,p.y,col('light'),a*2,r)}var core=smooth((t-20)/24),R=28+core*Math.min(W,H)*.18,g=cx.createRadialGradient(W/2,H/2,0,W/2,H/2,R);g.addColorStop(0,rgba(col('light'),core*.12));g.addColorStop(1,rgba(col('gold'),0));cx.fillStyle=g;cx.beginPath();cx.arc(W/2,H/2,R,0,TAU);cx.fill();s.R=core*.8+couple*.2}
function catchingUp(){var p=1-Math.exp(-t/18),dist=Math.exp(-3.6*p),m=Math.min(W,H),cx0=W/2,cy=H/2;bg(.13);cx.globalCompositeOperation='lighter';dust(.25+p*.55);var ax=cx0-dist*W*.46+Math.sin(t*.21)*m*.03,ay=cy+Math.sin(t*.13)*m*.04*dist,bx=cx0+dist*W*.46+Math.cos(t*.19)*m*.03,by=cy-Math.sin(t*.17)*m*.04*dist;s.trails[0].push([ax,ay]);s.trails[1].push([bx,by]);if(s.trails[0].length>160){s.trails[0].shift();s.trails[1].shift()}var R=m*(.06+p*.24),g=cx.createRadialGradient(cx0,cy,0,cx0,cy,R*2.2);g.addColorStop(0,rgba(col('light'),(.012+p*.085)*.55));g.addColorStop(1,rgba(col('gold'),0));cx.fillStyle=g;cx.beginPath();cx.arc(cx0,cy,R*2.2,0,TAU);cx.fill();var span=Math.hypot(bx-ax,by-ay),ang=Math.atan2(by-ay,bx-ax),mx=(ax+bx)/2,my=(ay+by)/2;cx.save();cx.translate(mx,my);cx.rotate(ang);for(var i=-6;i<=6;i++){cx.strokeStyle=rgba(col('gold'),p*.028*(1-Math.abs(i)/7));cx.beginPath();cx.moveTo(-span/2,0);cx.quadraticCurveTo(0,i*m*.018*p,span/2,0);cx.stroke()}cx.restore();dot(ax,ay,col('blue'),.25+p*.5,2+p*2);dot(bx,by,col('rose'),.25+p*.5,2+p*2);s.R=p}
function realPart(){bg(.075);cx.globalCompositeOperation='lighter';dust(.25);var m=Math.min(W,H)*.32,cx0=W/2,cy=H/2;cx.strokeStyle=rgba(col('gold'),.03+Math.min(s.heat.length*.004,.12));cx.beginPath();cx.moveTo(0,cy);cx.lineTo(W,cy);cx.stroke();if(Math.random()>.988&&s.pairs.length<36)spawnPair();for(var i=s.pairs.length-1;i>=0;i--){var p=s.pairs[i];p.p+=.012;p.b*=.996;p.w+=(1-p.b)*.003;var x=cx0+p.a*m,y=cy-p.b*m,y2=cy+p.b*m;dot(x,y,col('blue'),.08+p.w*.22,2+p.z);dot(x,y2,col('blue'),.08+p.w*.22,2+p.z);cx.strokeStyle=rgba(col('violet'),p.w*.05);cx.beginPath();cx.moveTo(x,y);cx.lineTo(x,y2);cx.stroke();if(p.b<.018){s.heat.push({x:x,y:cy,l:1,z:p.z});s.pairs.splice(i,1)}}for(i=s.heat.length-1;i>=0;i--){var h=s.heat[i];h.l-=.004;if(h.l<=0){s.heat.splice(i,1);continue}dot(h.x,h.y,col('gold'),.15+h.l*.35,1.6+h.z)}s.R=Math.min(1,s.heat.length/18)}
function twoVoices(){bg(.11);cx.globalCompositeOperation='lighter';dust(.35);var a=s.points[0],b=s.points[1],K=.5+.5*Math.sin(t*.09);a.p+=.018;b.p+=.018*PHI+(K*.006*Math.sin(a.p-b.p));for(var i=0;i<2;i++){var p=s.points[i],x=W*(.38+i*.24)+Math.sin(p.p)*50,y=H/2+Math.cos(p.p)*35;dot(x,y,i?col('rose'):col('blue'),.35,5);p.x=x;p.y=y}cx.strokeStyle=rgba(col('gold'),.04+K*.08);cx.beginPath();cx.moveTo(a.x,a.y);cx.quadraticCurveTo(W/2,H/2-120*K,b.x,b.y);cx.stroke();s.R=K}
function strings(){bg(.11);cx.globalCompositeOperation='lighter';dust(.28);for(var i=0;i<s.points.length;i++){var p=s.points[i];p.p+=.012+p.o*.006;var amp=20+Math.sin(p.p)*8;cx.strokeStyle=rgba(col(i===6?'light':'gold'),.08+Math.max(0,Math.sin(p.p))*.08);cx.beginPath();for(var y=H*.18;y<H*.82;y+=8){var x=p.x+Math.sin(y*.035+p.p)*amp*(1-Math.abs(y-H/2)/(H*.42));if(y===H*.18)cx.moveTo(x,y);else cx.lineTo(x,y)}cx.stroke()}s.R=.55+.25*Math.sin(t*.4)}
function stillHere(){var still=clamp((performance.now()-s.lastMove)/9000,0,1);bg(.18-still*.09);cx.globalCompositeOperation='lighter';for(var i=0;i<s.points.length;i++){var p=s.points[i];p.p+=.004*p.o+still*.006;p.x+=(W/2-p.x)*still*.0007;p.y+=(H/2-p.y)*still*.0007;var br=.5+.5*Math.sin(p.p),rr=p.r*(.45+br*.45+still*.7),a=(.004+still*.035)*(br*.8+.2);var g=cx.createRadialGradient(p.x,p.y,0,p.x,p.y,rr);g.addColorStop(0,rgba(col('light'),a*.55));g.addColorStop(.45,rgba(col('blue'),a*.18));g.addColorStop(1,rgba(col('blue'),0));cx.fillStyle=g;cx.beginPath();cx.arc(p.x,p.y,rr,0,TAU);cx.fill()}var pulse=.5+.5*Math.sin(t*.33),cg=cx.createRadialGradient(W/2,H/2,0,W/2,H/2,Math.min(W,H)*(.18+still*.22));cg.addColorStop(0,rgba(col('light'),still*(.025+pulse*.018)));cg.addColorStop(1,rgba(col('gold'),0));cx.fillStyle=cg;cx.fillRect(0,0,W,H);s.R=still;if(word)word.textContent=still>.74?'the room was already breathing':still>.38?'quiet has a shape':'move less; listen longer'}
function field(){bg(.10);cx.globalCompositeOperation='lighter';dust(.5);for(var i=0;i<s.points.length;i++){var p=s.points[i];p.p+=.01+p.o*.006;dot(p.x+Math.cos(p.p)*12,p.y+Math.sin(p.p*.7)*12,col(i%3===0?'rose':i%3===1?'blue':'gold'),.03+(.5+.5*Math.sin(p.p))*.08,1+(.5+.5*Math.sin(p.p))*2)}s.R=.5+.25*Math.sin(t*.2)}
function step(){t+=reduced?.006:.016;var m=modeName();if(m==='first-frequency')firstFrequency();else if(m==='catching-up')catchingUp();else if(m==='real-part')realPart();else if(m==='two-voices')twoVoices();else if(m==='strings')strings();else if(m==='still-here')stillHere();else field();cx.globalCompositeOperation='source-over';s.T=1-s.R;if(meter)meter.textContent='R='+s.R.toFixed(3)+' · T='+s.T.toFixed(3);if(word&&cfg.phrases&&cfg.phrases.length&&m!=='still-here')word.textContent=cfg.phrases[Math.min(cfg.phrases.length-1,Math.floor(t/12)%cfg.phrases.length)];requestAnimationFrame(step)}
cv.addEventListener('pointerdown',function(){s.lastMove=performance.now();if(modeName()==='catching-up'){t=0;s.trails=[[],[]]}else if(modeName()==='real-part'){spawnPair();spawnPair()}else if(modeName()==='strings'){for(var i=0;i<s.points.length;i++)s.points[i].p+=Math.random()*2}});addEventListener('pointermove',function(){s.lastMove=performance.now()},{passive:true});
resize();addEventListener('resize',resize,{passive:true});step();
})();
