(function(){
'use strict';
var cv=document.getElementById('g-canvas');
if(!cv)return;
var cx=cv.getContext('2d');
var cfg=window.GUMP_ART||{};
var W=0,H=0,dpr=1,t=0,frame=0,TAU=Math.PI*2,PHI=(1+Math.sqrt(5))/2,GA=2.39996322;
var state={points:[],dust:[],trails:[],heat:[],pairs:[],rings:[],phrase:0,R:0,T:1};
var reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
var word=document.querySelector('.g-word');
var meter=document.querySelector('.g-meter');
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
function smooth(x){x=clamp(x,0,1);return x*x*(3-2*x)}
function mix(a,b,u){return a+(b-a)*u}
function rgba(c,a){return 'rgba('+c[0]+','+c[1]+','+c[2]+','+clamp(a,0,1).toFixed(4)+')'}
function color(name){var p={gold:[184,117,58],light:[232,207,160],rose:[210,150,120],blue:[110,160,210],green:[90,173,90],violet:[190,140,200],dark:[8,5,4],amber:[201,164,74]};return p[name]||p.gold}
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;cv.width=W*dpr;cv.height=H*dpr;cx.setTransform(dpr,0,0,dpr,0,0);init(true)}
function seedDust(n){state.dust=[];for(var i=0;i<n;i++)state.dust.push({x:Math.random()*W,y:Math.random()*H,p:Math.random()*TAU,v:Math.random(),z:.4+Math.random()*.9})}
function init(force){var mode=cfg.mode||'field';if(force&&state._mode===mode&&state.points.length)return;state._mode=mode;state.points=[];state.trails=[];state.heat=[];state.pairs=[];state.rings=[];seedDust(reduced?140:420);var i,a,r,s;
 if(mode==='first-frequency'){for(i=0;i<137;i++){a=i*GA;r=Math.sqrt(i)/Math.sqrt(137)*Math.min(W,H)*.35;state.points.push({x:W/2+Math.cos(a)*r,y:H/2+Math.sin(a)*r,p:Math.random()*TAU,o:.2+Math.random()*.6,lock:0})}}
 else if(mode==='catching-up'){state.points=[{x:0,y:0,p:0},{x:0,y:0,p:Math.PI}];state.trails=[[],[]]}
 else if(mode==='real-part'){for(i=0;i<24;i++)spawnPair();}
 else if(mode==='two-voices'){for(i=0;i<2;i++)state.points.push({x:W*(.38+i*.24),y:H/2,p:i*Math.PI,o:i?1.618:1,r:70})}
 else if(mode==='strings'){for(i=0;i<13;i++)state.points.push({x:W*(.14+i*.06),y:H*.22,p:Math.random()*TAU,o:.4+i*.08,hit:0})}
 else {for(i=0;i<137;i++){a=i*GA;r=Math.sqrt(i)/Math.sqrt(137)*Math.min(W,H)*.34;state.points.push({x:W/2+Math.cos(a)*r,y:H/2+Math.sin(a)*r,p:Math.random()*TAU,o:.2+Math.random()*.8})}}
}
function spawnPair(){state.pairs.push({a:(Math.random()-.5)*1.6,b:.2+Math.random()*.75,p:Math.random()*TAU,s:.45+Math.random()*.75,w:0,born:t})}
function background(alpha){var bg=cfg.bg||[6,3,2];cx.fillStyle='rgba('+bg[0]+','+bg[1]+','+bg[2]+','+alpha.toFixed(3)+')';cx.fillRect(0,0,W,H)}
function dust(memory){for(var i=0;i<state.dust.length;i++){var d=state.dust[i];d.p+=.006+memory*.012;d.v=d.v*.985+(Math.sin(d.p+i)*.5+.5)*memory*.025;d.x+=Math.cos(d.p)*(.08+memory*.22)*d.z;d.y+=Math.sin(d.p*.7)*(.08+memory*.18)*d.z;if(d.x<0)d.x=W;if(d.x>W)d.x=0;if(d.y<0)d.y=H;if(d.y>H)d.y=0;cx.fillStyle=rgba(color('gold'),.008+d.v*.075);cx.fillRect(d.x,d.y,1,1)}}
function firstFrequency(){var memory=smooth((t-1)/9),signal=smooth((t-5)/18),couple=smooth((t-14)/28);background(.17-memory*.09);cx.globalCompositeOperation='lighter';dust(memory);for(var i=0;i<state.points.length;i++){var p=state.points[i];p.p+=.004+signal*.017;p.lock+=(couple-p.lock)*.01;p.x+=(W/2-p.x)*p.lock*.004;p.y+=(H/2-p.y)*p.lock*.004;var br=.5+.5*Math.sin(p.p),a=(signal*.05+br*.03*signal)*(1-i/190),rr=1+br*2+couple*2;var g=cx.createRadialGradient(p.x,p.y,0,p.x,p.y,rr*9);g.addColorStop(0,rgba(color('light'),a*.8));g.addColorStop(1,rgba(color('gold'),0));cx.fillStyle=g;cx.fillRect(p.x-rr*9,p.y-rr*9,rr*18,rr*18);cx.fillStyle=rgba(color('light'),Math.min(.8,a*2));cx.beginPath();cx.arc(p.x,p.y,rr*.34,0,TAU);cx.fill()}var core=smooth((t-20)/24),R=28+core*Math.min(W,H)*.18,pulse=.5+.5*Math.sin(t*1.868);var cg=cx.createRadialGradient(W/2,H/2,0,W/2,H/2,R);cg.addColorStop(0,rgba(color('light'),core*(.08+pulse*.05)));cg.addColorStop(.38,rgba(color('gold'),core*.035));cg.addColorStop(1,rgba(color('gold'),0));cx.fillStyle=cg;cx.beginPath();cx.arc(W/2,H/2,R,0,TAU);cx.fill();state.R=core*.8+couple*.2}
function catchingUp(){var p=1-Math.exp(-t/18),dist=Math.exp(-3.6*p),m=Math.min(W,H),cx0=W/2,cy=H/2;background(.13);cx.globalCompositeOperation='lighter';dust(.25+p*.55);var ax=cx0-dist*W*.46+Math.sin(t*.21)*m*.03,ay=cy+Math.sin(t*.13)*m*.04*dist,bx=cx0+dist*W*.46+Math.cos(t*.19)*m*.03,by=cy-Math.sin(t*.17)*m*.04*dist;state.trails[0].push([ax,ay]);state.trails[1].push([bx,by]);if(state.trails[0].length>160){state.trails[0].shift();state.trails[1].shift()}var breath=.55+.45*Math.sin(t*.153),oneA=.012+p*.085,R=m*(.06+p*.24)*(1+breath*.08);var g=cx.createRadialGradient(cx0,cy,0,cx0,cy,R*2.2);g.addColorStop(0,rgba(color('light'),oneA*.55));g.addColorStop(.32,rgba(color('gold'),oneA*.18));g.addColorStop(1,rgba(color('gold'),0));cx.fillStyle=g;cx.beginPath();cx.arc(cx0,cy,R*2.2,0,TAU);cx.fill();var span=Math.hypot(bx-ax,by-ay),ang=Math.atan2(by-ay,bx-ax),midX=(ax+bx)/2,midY=(ay+by)/2;cx.save();cx.translate(midX,midY);cx.rotate(ang);for(var i=-6;i<=6;i++){cx.strokeStyle=rgba(color('gold'),p*.028*(1-Math.abs(i)/7));cx.lineWidth=.4+p*.9;cx.beginPath();cx.moveTo(-span/2,0);cx.quadraticCurveTo(0,i*m*.018*p,span/2,0);cx.stroke()}cx.restore();drawTrail(state.trails[0],color('blue'));drawTrail(state.trails[1],color('rose'));zero(ax,ay,color('blue'),p);zero(bx,by,color('rose'),p);state.R=p}
function drawTrail(tr,col){for(var i=0;i<tr.length;i++){var a=i/tr.length*.025;cx.fillStyle=rgba(col,a);cx.beginPath();cx.arc(tr[i][0],tr[i][1],1+i/tr.length*1.7,0,TAU);cx.fill()}}
function zero(x,y,col,p){var h=cx.createRadialGradient(x,y,0,x,y,46);h.addColorStop(0,rgba(col,.12+p*.28));h.addColorStop(.35,'rgba(0,0,0,.12)');h.addColorStop(1,rgba(col,0));cx.fillStyle=h;cx.beginPath();cx.arc(x,y,46,0,TAU);cx.fill();cx.fillStyle=rgba(color('light'),.25+p*.5);cx.beginPath();cx.arc(x,y,2+p*2,0,TAU);cx.fill()}
function realPart(){background(.075);cx.globalCompositeOperation='lighter';dust(.25);var m=Math.min(W,H)*.32,cx0=W/2,cy=H/2;cx.strokeStyle=rgba(color('gold'),.03+Math.min(state.heat.length*.004,.12));cx.beginPath();cx.moveTo(0,cy);cx.lineTo(W,cy);cx.stroke();cx.strokeStyle=rgba(color('blue'),.025);cx.beginPath();cx.moveTo(cx0,0);cx.lineTo(cx0,H);cx.stroke();if(Math.random()>.988&&state.pairs.length<36)spawnPair();for(var i=state.pairs.length-1;i>=0;i--){var p=state.pairs[i];p.p+=.012;p.b*=.996;p.w+=(1-p.b)*.003;var x=cx0+p.a*m,y=cy-p.b*m,y2=cy+p.b*m;var a=.08+p.w*.22;drawDot(x,y,color('blue'),a,2+p.s);drawDot(x,y2,color('blue'),a,2+p.s);cx.strokeStyle=rgba(color('violet'),p.w*.05);cx.beginPath();cx.moveTo(x,y);cx.lineTo(x,y2);cx.stroke();if(p.b<.018){state.heat.push({x:x,y:cy,l:1,s:p.s});state.pairs.splice(i,1)}}for(i=state.heat.length-1;i>=0;i--){var h=state.heat[i];h.l-=.004;if(h.l<=0){state.heat.splice(i,1);continue}var rr=(1-h.l)*42+12*h.s,g=cx.createRadialGradient(h.x,h.y,0,h.x,h.y,rr);g.addColorStop(0,rgba(color('light'),h.l*.12));g.addColorStop(.3,rgba(color('gold'),h.l*.06));g.addColorStop(1,rgba(color('gold'),0));cx.fillStyle=g;cx.beginPath();cx.arc(h.x,h.y,rr,0,TAU);cx.fill();drawDot(h.x,h.y,color('gold'),.15+h.l*.35,1.6+h.s)}state.R=Math.min(1,state.heat.length/18)}
function drawDot(x,y,col,a,r){var g=cx.createRadialGradient(x,y,0,x,y,r*7);g.addColorStop(0,rgba(col,a*.32));g.addColorStop(1,rgba(col,0));cx.fillStyle=g;cx.beginPath();cx.arc(x,y,r*7,0,TAU);cx.fill();cx.fillStyle=rgba(col,a);cx.beginPath();cx.arc(x,y,r,0,TAU);cx.fill()}
function generic(){background(.10);cx.globalCompositeOperation='lighter';dust(.5);for(var i=0;i<state.points.length;i++){var p=state.points[i];p.p+=.01+p.o*.006;var br=.5+.5*Math.sin(p.p),a=.03+br*.08,rr=1+br*2;drawDot(p.x+Math.cos(p.p)*12,p.y+Math.sin(p.p*.7)*12,color((i%3===0)?'rose':(i%3===1?'blue':'gold')),a,rr)}state.R=.5+.25*Math.sin(t*.2)}
function twoVoices(){background(.11);cx.globalCompositeOperation='lighter';dust(.35);var p0=state.points[0],p1=state.points[1],K=.5+.5*Math.sin(t*.09);p0.p+=.018;p1.p+=.018*PHI+(K*.006*Math.sin(p0.p-p1.p));var y=H/2;for(var i=0;i<2;i++){var p=state.points[i],x=W*(.38+i*.24)+Math.sin(p.p)*50;drawDot(x,y+Math.cos(p.p)*35,i?color('rose'):color('blue'),.35,5);p.x=x;p.y=y}cx.strokeStyle=rgba(color('gold'),.04+K*.08);cx.beginPath();cx.moveTo(p0.x,p0.y);cx.quadraticCurveTo(W/2,H/2-120*K,p1.x,p1.y);cx.stroke();state.R=K}
function strings(){background(.11);cx.globalCompositeOperation='lighter';dust(.28);for(var i=0;i<state.points.length;i++){var p=state.points[i];p.p+=.012+p.o*.006;var x=p.x,amp=20+Math.sin(p.p)*8;cx.strokeStyle=rgba(color(i===6?'light':'gold'),.08+Math.max(0,Math.sin(p.p))*.08);cx.beginPath();for(var y=H*.18;y<H*.82;y+=8){var xx=x+Math.sin(y*.035+p.p)*amp*(1-Math.abs(y-H/2)/(H*.42));if(y===H*.18)cx.moveTo(xx,y);else cx.lineTo(xx,y)}cx.stroke()}state.R=.55+.25*Math.sin(t*.4)}
function step(){t+=reduced?.006:.016;frame++;var mode=cfg.mode||'field';if(mode==='first-frequency')firstFrequency();else if(mode==='catching-up')catchingUp();else if(mode==='real-part')realPart();else if(mode==='two-voices')twoVoices();else if(mode==='strings')strings();else generic();cx.globalCompositeOperation='source-over';state.T=1-state.R;if(meter)meter.textContent='R='+state.R.toFixed(3)+' · T='+state.T.toFixed(3);if(word&&cfg.phrases&&cfg.phrases.length){var idx=Math.min(cfg.phrases.length-1,Math.floor(t/12)%cfg.phrases.length);word.textContent=cfg.phrases[idx]}requestAnimationFrame(step)}
cv.addEventListener('pointerdown',function(e){if((cfg.mode||'')==='catching-up'){t=0;state.trails=[[],[]]}else if((cfg.mode||'')==='real-part'){spawnPair();spawnPair()}else if((cfg.mode||'')==='strings'){for(var i=0;i<state.points.length;i++)state.points[i].p+=Math.random()*2}else{state.R=Math.min(1,state.R+.1)}});
resize();addEventListener('resize',resize,{passive:true});step();
})();
