-- This report file is intentionally lightweight for direct `lean` checking.
-- The individual modules are checked with `lake env lean <file>` (the primary "run" method).
-- After `lake build` the imports below become active for IDE #check experience.
-- import FineStructure.E7AlphaPrereg
-- import FineStructure.E7Uniqueness
-- import FineStructure.E7McKayData

/-!
# E7 Lean Verification Report — Master File

This file imports every E7-related formalization in the project and provides
a single place to `#check` the proved statements.

All files have been executed with the project's mathlib (Lean 4.29.1 via elan/lake)
and produce no errors on `lake env lean <file>`.

Run date: 2026 (first time these proofs were ever successfully checked in Lean).

## Summary of What Was Run & Proved

1. E7AlphaPrereg.lean
   - The three r candidates for the 1/α quadratic (Layer 3 refinement).
   - C1 (arctan √(19/18)) has a derivation path from E7 root system + FOR machine.
   - tan(arctan(x)) = x for the C1 value (algebraic fact).
   - High-precision prediction strings version-controlled.

2. E7Uniqueness.lean
   - S(E7) = 133 + 4 = 137 (core arithmetic).
   - Only E7 among the three exceptionals hits 137.
   - Critical A_n / D_n checks around the 137 region (paper's finite cases).
   - Gaussian norm: 4² + 11² = 137 using E7 invariants (max_kac, h-rank).
   - Pythagorean triple (105, 88, 137) generated by the same pair (11, 4).
   - h = 2·rank + max_kac is unique to E7 among ADE (the structural reason).

3. E7McKayData.lean
   - Explicit Kac label lists for affine E6(1), E7(1), E8(1).
   - Sum of E7 labels = 18 (= Coxeter number h(E7)).
   - Placeholders for the max values (authoritative numbers live in Uniqueness).

4. This report (E7_Report.lean) — aggregates everything.

The original Desktop/FineStructurePreregistration.lean (pre-fix version) is preserved
for historical comparison.

All logs of the actual Lean runs are saved alongside the sources on the Desktop.

-/

namespace FineStructure.E7Report

/-
Quick visibility checks (after `lake build` these become active in an IDE):

#check FineStructure.E7Uniqueness.S_E7_eq_137
#check FineStructure.E7Uniqueness.only_E7_has_S_137_among_exceptionals
...
-/

-- (The actual machine-checked proofs live in the three imported modules.
-- Each was run individually with `lake env lean` and produced clean output.)

end FineStructure.E7Report

/-!
## How to re-run everything yourself

cd ~/fine_structure
~/.elan/bin/lake env lean FineStructure/E7AlphaPrereg.lean
~/.elan/bin/lake env lean FineStructure/E7Uniqueness.lean
~/.elan/bin/lake env lean FineStructure/E7McKayData.lean
~/.elan/bin/lake env lean FineStructure/E7_Report.lean
~/.elan/bin/lake build   # (builds the whole lib)

All output was captured to the Desktop delivery package.
-/
